version: "3.8"
services:
  application:
    build:
      context: ../../../.. # Spring 프로젝트 경로, 현재 컨트롤러까지 죄다 domain에 있어서 일단 domain으로 함
      dockerfile: ./mpl-domain/Dockerfile  # 루트 기준 Dockerfile 경로 지정
    image: mpl-domain:local-dev # 추후에 AWS에 배포할 경우, AWS계정번호.dkr.ecr.ap-northeast-2.amazonaws.com/mpl-domain:develop 으로 해야함
    ports:
      - 7070:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=rabbitmq
      - TZ=Asia/Seoul  # <-- timezone 설정 추가
      # JVM timezone 설정 추가 및 JVM 힙 메모리 설정 추가
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul  -Xms512m -Xmx1g
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=https://api.themoviedb.org/3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - infra-net
    # 컨테이너 메모리 제한 설정 ▼▼▼
    deploy:
      resources:
        limits:
          memory: 1g # 최대 1g 메모리 사용
          cpus: '4.0' # 최대 4코어
        reservations:
          memory: 512m # 최대 512mb 메모리 사용
          cpus: '0.5' # 최대 0.5코어 사용

networks:
  infra-net:
    external: true