version: "3"

services:
# 중앙 로그 수집
  filebeat:
    build: ./filebeat
    container_name: filebeat
    user: root # 호스트 파일 접근 권한을 위해 root로 실행
    volumes:
      # 컨테이너 메타데이터 수집을 위해 Docker 소켓 연결
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Docker가 로그를 저장하는 호스트의 디렉터리를 Filebeat 컨테이너에 연결
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # filebeat가 마지막으로 읽은 위치를 기억하기 위한 데이터 볼륨
      - filebeat-data:/usr/share/filebeat/data
    networks:
      - infra-net

volumes:
  filebeat-data:

networks:
  infra-net:
    driver: bridge