version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - es-data:/usr/share/elasticsearch/data # 데이터 영속성을 위한 볼륨
    ports:
      - "9200:9200"
    networks:
      - log-net # 서비스 간 통신을 위한 네트워크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5

# 중앙 로그 수집
  filebeat:
    build: ./filebeat
    container_name: filebeat
    environment:
      ES_HOST: "${ES_HOST}"
      ES_USERNAME: "${ES_USERNAME}"
      ES_PASSWORD: "${ES_PASSWORD}"
    user: root # 호스트 파일 접근 권한을 위해 root로 실행
    volumes:
      # 컨테이너 메타데이터 수집을 위해 Docker 소켓 연결
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Docker가 로그를 저장하는 호스트의 디렉터리를 Filebeat 컨테이너에 연결
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # filebeat가 마지막으로 읽은 위치를 기억하기 위한 데이터 볼륨
      - filebeat-data:/usr/share/filebeat/data
    networks:
      - log-net
    depends_on:
      - elasticsearch

# 지금 당장 사용할 것 아니라서 주석 처리
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.19.2
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_HOSTS : "${ES_HOST}"
#      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "${KIBANA_ENCRYPTION_KEY}"
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - log-net

volumes:
  es-data:
  filebeat-data:

networks:
  log-net:
    driver: bridge