# nginx/docker-compose.yml
version: "3.8"
services:
  nginx:
    container_name: 'nginx'
    image: nginx
    ports:
      - 8080:8080
    #      - 80:80
    #      - 443:443
    environment:
      - TZ=Asia/Seoul  # <-- timezone 설정 추가
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../../mpl-domain/src/main/resources/static:/usr/share/nginx/html:ro # 프론트엔드 빌드 결과물 마운트
    networks:
      - infra-net

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - infra-net

volumes:
  filebeat-data:
  redis-data:

networks:
  infra-net:
    name: infra-net
    driver: bridge