spring:
  config:
    activate:
      on-profile: dev
#  레디스 지금 당장 사용 안 할 예정이라서 아래 내용 추가함
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  datasource:
    url: jdbc:h2:file:~/testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
    open-in-view: true
  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  level:
    org:
      hibernate: warn
      springframework:
        web: warn # 스프링 웹 관련 로그를 줄입니다.
        data: warn