spring:
  config:
    activate:
      on-profile: docker
  # docker-compose.yml에서 환경 변수로 주입한 값을 사용합니다.
  # 이 값들은 docker-compose.yml에 정의된 값이 없을 경우 사용될 기본값(fallback)입니다.
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mpl_db}
    username: ${SPRING_DATASOURCE_USERNAME:mpl}
    password: ${SPRING_DATASOURCE_PASSWORD:mpl!}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # 현재 사용중인 커넥션 수
      minimum-idle: 5 # 유휴 상태인 커넥션 수
      idle-timeout: 60000
  jpa:
    # docker-compose.yml에서 환경 변수로 주입한 값을 사용합니다.
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    # PostgreSQL에 맞는 Dialect를 명시적으로 설정합니다.
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false # 개발 중에는 실행되는 쿼리를 확인하는 것이 유용합니다.
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  tomcat:
    threads:
      max: 40 #최대 스레드 갯수
    accept-count: 100 #연결 대기 큐 크기(스레드 모두 사용중일 때, 대기 시킬 공간)

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN